version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  golang-app:
    container_name: golang-app
    image: golang-app
    restart: always
    ports:
      - "8080:8080"